### ISSUE TITLE
Lỗi khi xem 1 video

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#11]
Khi xem trang chủ chưa thấy hiện video, chỉ là 1 trang trắng chưa có nội dung nếu để hiện theo chuyên mục
Lỗi khi xem 1 video . Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined index: playlist_id in file /modules/videos/funcs/detail.php on line 293
Nên chú ý Nên chú ý: Undefined index: playlist_id in file /modules/videos/funcs/detail.php on line 404

**Comment by anhyeuviolet** [comment]
Fixed.
https://github.com/anhyeuviolet/module-videos/commit/f558313ec03cef84eb11f0061f380b208d73888b

**Comment by anhutbeo** [comment]
Mình test sơ qua thôi. Tối về test kĩ rồi báo bạn sau. Mình ra ngoài xíu có
việc
Vào 19-11-2015 10:06, "Kenny Nguyen" notifications@github.com đã viết:

**Comment by anhyeuviolet** [comment]
Ok ! Cảm ơn bạn nha ! :dancer:
