### ISSUE TITLE
Đề xuất

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#12]
Cố định chiều ngang và cao của hình khi xem trang chủ, cái to  cái nhỏ mất thẩm mỹ.
![1](https://cloud.githubusercontent.com/assets/10916826/11262797/26fd49b6-8eb6-11e5-8b93-463b30269997.png)

Khi xem chủ đề theo dạng lưới
![2](https://cloud.githubusercontent.com/assets/10916826/11262804/3995a78a-8eb6-11e5-8538-75869295bbac.png)

Khi xem 1 video, phần liên kết video mới hơn, cũ hơn nên để hình chứ để link nhìn cũng xấu
![3](https://cloud.githubusercontent.com/assets/10916826/11262818/650ca008-8eb6-11e5-941b-b1ac282b034d.png)

**Comment by anhyeuviolet** [comment]
Fixed
https://github.com/anhyeuviolet/module-videos/commit/c89fc5686a2a6c462b53402dcc10578556e0758a

**Comment by anhyeuviolet** [comment]
Bạn tải code mới, đè lên code cũ để xem tình hình thế nào nhé.

**Comment by anhutbeo** [comment]
Đã cài lại mới
Khi xem trang chủ "Dạng lưới theo chủ đề" Cấu hình mặc định 270x200 nó không tự co giãn, để thấp hơn thì ok

![2015-11-20_092212](https://cloud.githubusercontent.com/assets/10916826/11290334/7cc4bdc2-8f68-11e5-8e51-ef08ca133336.png)

Khi xem chủ 1 chủ đề để theo dạng lưới, mới lên trên thì ok.

![2015-11-20_092145](https://cloud.githubusercontent.com/assets/10916826/11290361/b7dac820-8f68-11e5-83f0-48cb7d29a272.png)

Phần video mới hơn, cũ hơn đã ok
![2015-11-20_092636](https://cloud.githubusercontent.com/assets/10916826/11290387/d99a0728-8f68-11e5-9f76-ed5ae9eb9efd.png)

**Comment by anhyeuviolet** [comment]
Fix phần trang chủ.
https://github.com/anhyeuviolet/module-videos/commit/61debe71c89e8534e6bb1cf23f3664b939f4684d

Bạn test nhé. Phải cài lại module.

**Comment by anhutbeo** [comment]
Good rồi bạn nhé :)

**Comment by anhyeuviolet** [comment]
Closed !
