### ISSUE TITLE
Lỗi tag

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#13]
![1](https://cloud.githubusercontent.com/assets/10916826/11262885/12f85a4a-8eb7-11e5-8b33-628390a1acbd.png)

**Comment by anhyeuviolet** [comment]
Fixed.
https://github.com/anhyeuviolet/module-videos/commit/c89fc5686a2a6c462b53402dcc10578556e0758a

**Comment by anhyeuviolet** [comment]
Nếu còn lỗi thì Re-open nhé.
