### ISSUE TITLE
Góp ý

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#14]
Phần thể hiện 1 video nên viết thêm cho nó phần
- Tác giả video ( ví dụ như tên tác giả nếu đó là 1 bài hát hay 1 video tự quay )
- Thể hiện video ( ví dụ như tên ca sỹ thể hiện nếu nó là 1 bài hát )
- Người upload
  (giống như block của modules photo)
  Khi lick vào tên 1 ai đó ( ví dụ nhạc sỹ hay ca sỹ ) nó liệt kê ra 1 trang có toàn bộ video của người đó.

**Comment by anhutbeo** [comment]
Phần Tags có thể giải quyết vấn đề này :)). Nhưng chỉ sợ nhiều 1 site nhiều video mà tags chắc cũng không nhớ hết :))

**Comment by anhyeuviolet** [comment]
Cái này mình cũng đang nghĩ phương án. Không khó nhưng công việc khá là đồ sộ :D

**Comment by anhutbeo** [comment]
Mình cũng thấy vậy nên mới để là Góp ý :). Nhưng để Tags cho nó thì cũng tạm ổn rồi. :)

**Comment by anhyeuviolet** [comment]
Cái này, mình làm được. 
Nhưng bạn cho ý kiến cái này xíu : Vì thông tin Uploader chính là 1 thành viên của NukeViet. Khi đó nó gọi các thông tin cá nhân từ module user.
Vấn để sẽ nảy sinh khi mà user đó bị xoá, huỷ kích hoạt ... Các thông tin sẽ không còn nữa khi truy vấn theo user. 
Thế thì làm thế nào giờ ?

**Comment by anhyeuviolet** [comment]
Fixed.
https://github.com/anhyeuviolet/module-videos/commit/61debe71c89e8534e6bb1cf23f3664b939f4684d

**Comment by anhyeuviolet** [comment]
Bạn test chức năng này xem thế nào nhé.
Uploader sẽ hiện ra trang chủ cùng.
Còn tác giả và người thể hiện thì nó trong tab mở rộng, khi thêm Video nhé.

**Comment by anhyeuviolet** [comment]
Closed !
