### ISSUE TITLE
Lỗi trên giao diện mobile

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#15]
Do không có phần giới thiệu video nên tiêu đề nó đẩy hết lên trên. Nên cho nó nằm dưới hình minh họa
![1](https://cloud.githubusercontent.com/assets/10916826/11263922/be113dde-8ec1-11e5-9878-33e049afb578.png)

**Comment by anhyeuviolet** [comment]
Cái này là trên máy tính rồi thu nhỏ giao diện hay là mobile luôn bạn ?
// Ah. Hiểu ròi. Mình đang fix.

**Comment by anhyeuviolet** [comment]
Đã fix. Tạm đóng.
