### ISSUE TITLE
Báo Lỗi khi xem 1 video

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#19]
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined index: playlist_id in file /modules/videos/funcs/detail.php on line 349

**Comment by anhyeuviolet** [comment]
Fixed ! 
https://github.com/anhyeuviolet/module-videos/commit/5203e090300b27aee2b581d52e896f28e5843a2f
