### ISSUE TITLE
Lỗi Playlist trong admin

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#20]
Lỗi cảnh báo: Missing argument 1 for nv_show_playlist_cat_list(), called in D:\wamp\www\utbeo1612\modules\videos\admin\playlists.php on line 127 and defined in file /modules/videos/admin.functions.php on line 565

**Comment by anhutbeo** [comment]
Cảnh báo Lỗi khi xem playlist ngoài site
Thông báo từ Hệ thống
Nên chú ý Nên chú ý: Undefined variable: page_title in file /modules/videos/theme.php on line 573

**Comment by anhyeuviolet** [comment]
Fixed.
https://github.com/anhyeuviolet/module-videos/commit/4a920184b0045ce6047e149a38b87b68c41269e4
