### ISSUE TITLE
Góp ý

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#22]
Là modules video nên phần tag nên cho nó hiển thị theo dạng lưới, để hiển thị theo dạng danh sách không hay lắm. Còn mang âm hưởng của modules news :)
![1](https://cloud.githubusercontent.com/assets/10916826/11318711/04e1736c-9090-11e5-85fe-bc5ec642eccf.png)

**Comment by anhyeuviolet** [comment]
:(( viết lại TPL á.
Nói chứ cái này mình tham khảo Youtube thấy họ cũng làm vậy á :D

**Comment by anhutbeo** [comment]
Youtube hình nó nhỏ, nên nhìn nó đẹp. Còn mình hình thì to mà có 2 dòng text nên nhìn nó trống trải quá :)) hihi

**Comment by anhyeuviolet** [comment]
Bạn tải code mới về đè lên, xoá cache trình duyệt xem thế nào nhé.
Kích thước thì mình sẽ thêm chức năng để chỉnh được trong Cấu hình Module.

**Comment by anhutbeo** [comment]
mới vừa download mới cách đây khoảng 1 tiếng, về add thử 20 cái video để test thử, và định làm luôn cái theme đi kèm cái modules video này để share luôn khi modules này trình làng. :))

**Comment by anhyeuviolet** [comment]
Còn mấy cái nhỏ nhỏ nữa, sắp share rộng rãi được rồi.
Cố lên bạn ! :D

**Comment by anhyeuviolet** [comment]
Closed !

**Comment by anhutbeo** [comment]
Để tối cài mới luôn rồi test tất cả. Down về chép đè xóa cache không thấy gì hết. :)). Tối test luôn các block. Thấy sơ sơ là lỗi toàn bộ, chưa fix cái nào. Nếu kg dùng đến thì nên xóa bớt cho nhẹ :))

**Comment by anhyeuviolet** [comment]
Block thì nào hoàn thiện sẽ fix tất cả. Mớ này ko dùng lại được.
