### ISSUE TITLE
Tạo playlist chưa có phần hình minh họa

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#23]
Tạo playlist chưa có phần hình minh họa. kg có chổ để upload hình 
![1](https://cloud.githubusercontent.com/assets/10916826/11318733/70e13b6a-9090-11e5-9273-aa441fd5bfba.png)

**Comment by anhyeuviolet** [comment]
Nếu từ ngoài site thì chắc mình thêm dòng thông báo hotlink vào hoặc sẽ ko cho up ảnh minh hoạ, vì chính NV cũng hạn chế upload từ khách/thành viên.
Mình sẽ có hd chèn hotlink vào hoặc random các hình mặc định hệ thống vậy.

**Comment by anhutbeo** [comment]
Vậy thì cho chèn hotlink, random hình của hệ thống thì cũng có cái hạn chế vì thành viên có khi tìm kg được cho mình 1 cái hình ưng ý :)

**Comment by anhyeuviolet** [comment]
Fixed.
https://github.com/anhyeuviolet/module-videos/commit/fe851fcbd47423b002ad798a598b8ad415527551
