### ISSUE TITLE
Thể loại (groups) có thể hiển dưới dạng danh sách thể loại

### ISSUE THREAD

**Issue by anhyeuviolet** [anhyeuviolet/module-videos#33]

**Comment by anhutbeo** [comment]
Chưa thấy chức năng này :))

**Comment by anhyeuviolet** [comment]
Hiz ... đang viết, đang viết ...

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-videos/commit/f883b6466bb6af0bb59fffb6a6f135222c1f08ad
