### ISSUE TITLE
Lỗi tên uploader 

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#34]
Khi bấm vào uploader với tên có dấu (ví dụ Út Beo) thì có link 
http://utbeovideo/index.php?language=vi&nv=videos&op=uploader/%C3%9At%20Beo. Nó trả về trang chủ, không hiện ra trang của uploader đó

**Comment by anhyeuviolet** [comment]
Uầy ! Cuộc sống không dễ dàng. Lỗi này căng hẳn. :dancer:

**Comment by anhutbeo** [comment]
hihi, modules member khi gọi tên thành viên nó ra dạng này
http://utbeovideo/users/memberlist/Ut-Beo-4de795cec16e1df8d1b54442dffc5288/
Bạn tham khảo thử xem

**Comment by anhyeuviolet** [comment]
Mình có xem thử, có cái là nó sẽ bị ảnh hưởng khi user bị xoá ....
Chắc sẽ làm truy vấn và link dạng khác.

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-videos/commit/f883b6466bb6af0bb59fffb6a6f135222c1f08ad

https://github.com/anhyeuviolet/module-videos/commit/84596e9091ef7209133a3decb9d03cdbaaf2e86c
