### ISSUE TITLE
Lỗi video từ những nguồn khác nhau

### ISSUE THREAD

**Issue by nguyengiakt** [anhyeuviolet/module-videos#43]
Hiện tại module lỗi error loading playlist not a valid rss feed. Có video được có video ko, mình đang tìm hiểu nguyên nhân
![a](https://cloud.githubusercontent.com/assets/2918834/14044878/8e999906-f2c7-11e5-98a1-a32f2286416b.jpg)
![b](https://cloud.githubusercontent.com/assets/2918834/14044879/8e9b25e6-f2c7-11e5-9df0-d01a882c0462.jpg)

**Comment by nguyengiakt** [comment]
Nếu giới thiệu ngắn gọn ít ký tự hoặc ko có j thì ko bị lỗi trên ![c](https://cloud.githubusercontent.com/assets/2918834/14045176/729d6360-f2ca-11e5-9dd8-1dc07eacdf67.jpg)

**Comment by nguyengiakt** [comment]
đó là giải pháp tạm thời có những video hometext vẫn dài nhưng vẫn hiện

**Comment by anhyeuviolet** [comment]
Bạn thử đưa một số link video mà có thể sinh lỗi nhé.
Lỗi này có thể do quá trình tạo playlist bị lỗi và báo ra player chứ theo mình thì hầu hết ko liên quan đến định dạng của video.
Ngoài ra Hometext cũng chưa hẳn là lý do. Mình muốn kiểm tra thêm.

**Comment by nguyengiakt** [comment]
http://samtuoingoclinh.com/videos/kon-tum/thanh-pho-kon-tum-27.html
đây nhé bạn, mình thử thêm dòng hometext dài thì nó bị. có 686 ký tự

**Comment by anhyeuviolet** [comment]
Bạn trích đoạn hometext lên đây.

**Comment by anhyeuviolet** [comment]
Không phải do dài hay ngắn là do trong đó có & các thể loại, rồi vài cái ký tự đặc biệt khác. Cảm ơn bạn !
Còn cái nào lỗi thì cho mình link để test cho chính xác nhé.

**Comment by anhyeuviolet** [comment]
Fixed.
https://github.com/anhyeuviolet/module-videos/commit/9a2b4de5e799f22fe7db0b0c9d81fa8dd102d318
Thanks @nguyengiakt , giờ bạn có thể cài đè code mới lên và up hometext thoải mái :dancers:
