### ISSUE TITLE
Lỗi gói cập nhật

### ISSUE THREAD

**Issue by quangcuong** [anhyeuviolet/module-videos#54]
Tôi dùng bản nukeviet 4.0.29 (nâng cấp từ bản 4.0.28). Trên hệ thống đã cài module-videos. Nhưng khi tiến hành nâng cấp thì được báo: "Bạn chưa cài đặt module này lên hệ thống do đó không có công việc nào cần thực hiện, đơn giản hãy xóa gói cập nhật này để website hoạt động trở lại". Mong ad kiểm tra lại. 
Cảm ơn!

**Comment by anhyeuviolet** [comment]
@quangcuong Hiện module Videos chưa phát hành bản nâng cấp nào, và việc nâng cấp NukeViet 4.0.28 lên 4.0.29 cũng không ảnh hưởng đến modules đang dùng.
Bạn có thể cung cấp link đến gói cập nhật mà bạn đã tải được không ?

**Comment by quangcuong** [comment]
Hôm qua tôi nhớ vào link này! https://github.com/anhyeuviolet/module-videos/wiki/C%E1%BA%ADp-nh%E1%BA%ADt-Videos-l%C3%AAn-0.1.10
Tôi down gói nâng cấp như sau: update_video-clip_to4.0.28

**Comment by quangcuong** [comment]
Gói update mình down đây (mình up lại lên google drive --> vì ở đây mình đính kèm nó không cho :"Unfortunately, we don't support that file type"
https://drive.google.com/drive/folders/0B1K7M2CUJQz9bjlySnRfX0RSUm8

**Comment by anhyeuviolet** [comment]
Vậy không phải của module này rồi.
Gói đó dành cho video-clip Ajax.
Gói cho Videos mình đang làm và test.
