### ISSUE TITLE
Hiện thị số liên kết không hợp lí

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#55]
Trong phần Quản lí chuyên mục video để hiện thị 3 tin thì khi xem trang chủ hiện thị 3 tin. Nhưng xem chủ đề đó nó cũng hiện thị có 3 tin (không hợp lí lắm :)) ) Còn nếu để hiện ví dụ 15 tin thì khi xem chuyên mục thì 15 tin ok, nhưng trang chủ nó cũng hiện 15 tin cho chuyên mục đó, nhìn xấu ... và nếu videos clip có nhiều chuyên mục thì nó hiện rất là nhiều tin ....

**Comment by anhyeuviolet** [comment]
Giải quyết như sau:
Tại trang chủ: Các chuyên mục hiện số tin theo cấu hình trong Quản lý chuyên mục.
Tại từng chuyên mục: Hiển thị theo "Số Videos được hiển thị trên một trang (Theo từng chuyên mục)" trong Cấu hình Modules.

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-videos/commit/376f06ebb20d782d5299ec19970e32558938fa4e
