### ISSUE TITLE
Lỗi tìm kiếm modules videos

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#56]
Chức năng tìm kiếm trên site sẽ bị lỗi toàn bộ nếu có cài thêm modules, nếu kg cài thì kg sao, hoặc bỏ file search.php trong modules thì tìm kiếm hoạt động bình thường

**Comment by anhyeuviolet** [comment]
Do thay đổi cấu trúc DB....

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-videos/commit/376f06ebb20d782d5299ec19970e32558938fa4e
