### ISSUE TITLE
Lỗi: Error loading playlist: Playlist load error: file not found

### ISSUE THREAD

**Issue by quangcuong** [anhyeuviolet/module-videos#58]
Sau khi nâng cấp xong bị lỗi như trên! Đang chạy thử trên localhost. XIn hướng dẫn cách khác phục

**Comment by anhyeuviolet** [comment]
Tạm thời, bạn tự sửa detail.php mà mình đã đánh dấu.
https://github.com/anhyeuviolet/module-videos/commit/1fca01a27d5dc8f16b7f68af7ac86595aae23cb3#diff-4d606ce872c5a7e5f3f1b277e091ac41L91

Chắc là do bạn dùng module ảo đúng không ?

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-videos/issues/57

**Comment by anhyeuviolet** [comment]
https://github.com/anhyeuviolet/module-videos/commit/947d94fb447b74469efaac6a08365c1fa6e6fdc1
