### ISSUE TITLE
Chức năng skip ads jwplaywer youtube

### ISSUE THREAD

**Issue by nguyengiakt** [anhyeuviolet/module-videos#59]
Chào bạn!
Nếu muốn có thêm skip ads jwplaywer như những trang video khác thì mình cấu hình chỗ nào?
Cảm ơn

**Comment by anhyeuviolet** [comment]
Chào bạn. Trước tiên phải chèn quảng cáo vào đã.
Hiện tại, mình chưa viết chức năng này.

**Comment by nguyengiakt** [comment]
không có cách nào để hiện youtube adsense vào hả bạn?

**Comment by anhyeuviolet** [comment]
Bạn chèn QC vào youtube, vì JWplayer không "ghi đè" các quảng cáo từ Youtube.

**Comment by nguyengiakt** [comment]
nó ko hiện bạn, mình nghiên cứu thêm cái này, có j chia sẻ code trên này, thks bạn

**Comment by nguyengiakt** [comment]
lỗi mình ko liên kết với tài khoản youtube nên ko hiện :)

**Comment by nguyengiakt** [comment]
nếu cho video tự động phát adsense ko xuất hiện
