### ISSUE TITLE
Mất video khác khi xem 1 video

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#60]
Lên phiên bản mới nhất không thấy các video cùng chủ đề khi xem 1 video clip. Khi xem thấy demo ở đây cũng bị như vậy 
http://nukeviet-hvt.rhcloud.com/videos/chuyen-muc-1/bich-phuong-rang-em-mai-o-ben-chillout-version-m-v-5.html

**Comment by anhyeuviolet** [comment]
Cái này là cố tình ấy. 
Bản sau mình sẽ thêm block hoặc chức năng tắt mở, chứ nó triển ra nhiều quá nhìn rối hết cả trang.

**Comment by anhutbeo** [comment]
à ra là thế. để vậy thì khi xem thấy nó ngắn quá. kg thấy video clip mới hơn hoặc củ hơn. hóng ... :))
