### ISSUE TITLE
Chức năng cho user tự upload video?

### ISSUE THREAD

**Issue by nguyengiakt** [anhyeuviolet/module-videos#62]
Dear bạn!
Module video bạn rất hay và sài chuẩn, nhưng hiện tại vẫn chưa cho người dùng tính năng upload lên video. Hy vọng tương lai bạn có thể viết thêm chức năng này 
Thks!

**Comment by anhyeuviolet** [comment]
Cảm ơn bạn !
Module này mình chỉ định hướng để chia sẻ là chính thôi.
Nên với user mình chỉ cấu hình để chia sẻ link qua youtube hoặc 1 hot link nào đó. Chút user upload lên thì được, nhưng ko quản lý được khi user đó vấn đề gì đó phát sinh.

**Comment by nguyengiakt** [comment]
đúng là chỉ cho họ úp link youtube thôi, chứ up lên server mình thì rất nặng, nhưng hiện giờ đã có chức năng đó?
thks

**Comment by anhyeuviolet** [comment]
@nguyengiakt Thử nhé bạn:
https://nukeviet-hvt.rhcloud.com/videos/user-video/
