### ISSUE TITLE
Thay đổi avatar cho module videos

### ISSUE THREAD

**Issue by matbuonvn** [anhyeuviolet/module-videos#68]
Em có tải module videos về và cài trên nuke 4.1beta1 thì thấy hiển thị avartar mặc định là 
http://www.gravatar.com/avatar/418a31b34032b7237679fb3c0ce8c27f?s=256&d=identicon&r=g
 Thế có cách nào thay đổi avart của người upload video lên không ạ.
Mong sớm hồi âm ạ!..

**Comment by anhyeuviolet** [comment]
Vào đây tạo nhé bạn.
https://en.gravatar.com/

**Comment by matbuonvn** [comment]
Em tạo tài khoản rồi nhưng không biết làm thế nào để hiển thị trong module videos ạ. Bác chỉ em với được không ạ

**Comment by anhyeuviolet** [comment]
@matbuonvn cái email của tài khoản trong NukeViet phải khớp với cái mail bạn định dùng trên Gavatar nhé.

**Comment by matbuonvn** [comment]
Em đã lấy đúng email 2 bên rất khớp mà như hình ạ[](http://i.imgur.com/zKMvcVC.png)

**Comment by matbuonvn** [comment]
[http://i.imgur.com/zKMvcVC.png](url)

**Comment by matbuonvn** [comment]
Mà nó vẫn không thấy thay đổi avatar ạ
