### ISSUE TITLE
[Hỏi] Cập nhật 2.05

### ISSUE THREAD

**Issue by anhutbeo** [anhyeuviolet/module-videos#69]
Mình thấy có cập nhật lên 0.2.05 mà không thấy có hướng dẫn. anhyeuviolet chỉ giáo với ạ. Thanks đang dùng 0.2.04

**Comment by anhyeuviolet** [comment]
Bạn xem Wiki nhé:

https://github.com/anhyeuviolet/module-videos/wiki/%5BC%E1%BA%ADp-nh%E1%BA%ADt%5D-C%E1%BA%ADp-nh%E1%BA%ADt-Videos-l%C3%AAn-0.2.05
